tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-primary": "var(--color-on-primary)",
                "surface-tint": "var(--color-surface-tint)",
                "outline-variant": "var(--color-outline-variant)",
                "error": "var(--color-error)",
                "on-primary-fixed": "var(--color-on-primary-fixed)",
                "error-container": "var(--color-error-container)",
                "on-tertiary": "var(--color-on-tertiary)",
                "surface-container": "var(--color-surface-container)",
                "primary": "var(--color-primary)",
                "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
                "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
                "on-background": "var(--color-on-background)",
                "background": "var(--color-background)",
                "secondary": "var(--color-secondary)",
                "tertiary-container": "var(--color-tertiary-container)",
                "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
                "surface-variant": "var(--color-surface-variant)",
                "surface-dim": "var(--color-surface-dim)",
                "on-error-container": "var(--color-on-error-container)",
                "inverse-primary": "var(--color-inverse-primary)",
                "surface-container-highest": "var(--color-surface-container-highest)",
                "on-tertiary-container": "var(--color-on-tertiary-container)",
                "surface-container-lowest": "var(--color-surface-container-lowest)",
                "on-primary-container": "var(--color-on-primary-container)",
                "inverse-surface": "var(--color-inverse-surface)",
                "primary-fixed": "var(--color-primary-fixed)",
                "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
                "secondary-container": "var(--color-secondary-container)",
                "on-secondary": "var(--color-on-secondary)",
                "inverse-on-surface": "var(--color-inverse-on-surface)",
                "on-secondary-container": "var(--color-on-secondary-container)",
                "on-surface": "var(--color-on-surface)",
                "surface-container-low": "var(--color-surface-container-low)",
                "surface": "var(--color-surface)",
                "surface-bright": "var(--color-surface-bright)",
                "tertiary": "var(--color-tertiary)",
                "secondary-fixed": "var(--color-secondary-fixed)",
                "surface-container-high": "var(--color-surface-container-high)",
                "outline": "var(--color-outline)",
                "primary-fixed-dim": "var(--color-primary-fixed-dim)",
                "on-error": "var(--color-on-error)",
                "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
                "on-surface-variant": "var(--color-on-surface-variant)",
                "on-secondary-fixed": "var(--color-on-secondary-fixed)",
                "tertiary-fixed": "var(--color-tertiary-fixed)",
                "primary-container": "var(--color-primary-container)",
                "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "margin-mobile": "16px",
                "margin-desktop": "40px",
                "unit": "8px",
                "gutter": "24px",
                "container-max": "1200px"
            },
            "fontFamily": {
                "body-lg": ["Lora", "serif"],
                "headline-md": ["Lora", "serif"],
                "headline-xl": ["Lora", "serif"],
                "headline-lg": ["Lora", "serif"],
                "body-md": ["Lora", "serif"],
                "headline-lg-mobile": ["Lora", "serif"],
                "caption": ["Lora", "serif"],
                "label-md": ["Lora", "serif"]
            },
            "fontSize": {
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
                "caption": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
                "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}]
            }
        },
    },
}