tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-primary": "#ffffff",
                "surface-tint": "#a8381c",
                "outline-variant": "#dfc0b8",
                "error": "#ba1a1a",
                "on-primary-fixed": "#3c0700",
                "error-container": "#ffdad6",
                "on-tertiary": "#ffffff",
                "surface-container": "#f1ede8",
                "primary": "#9c2f14",
                "on-tertiary-fixed": "#2b1700",
                "secondary-fixed-dim": "#b8cf88",
                "on-background": "#1c1c19",
                "background": "#fdf9f4",
                "secondary": "#52652a",
                "tertiary-container": "#946425",
                "on-secondary-fixed-variant": "#3b4d14",
                "surface-variant": "#e6e2dd",
                "surface-dim": "#ddd9d5",
                "on-error-container": "#93000a",
                "inverse-primary": "#ffb4a2",
                "surface-container-highest": "#e6e2dd",
                "on-tertiary-container": "#ffefe1",
                "surface-container-lowest": "#ffffff",
                "on-primary-container": "#ffeeea",
                "inverse-surface": "#31302d",
                "primary-fixed": "#ffdad2",
                "on-primary-fixed-variant": "#872106",
                "secondary-container": "#d4eca2",
                "on-secondary": "#ffffff",
                "inverse-on-surface": "#f4f0eb",
                "on-secondary-container": "#576b2f",
                "on-surface": "#1c1c19",
                "surface-container-low": "#f7f3ee",
                "surface": "#fdf9f4",
                "surface-bright": "#fdf9f4",
                "tertiary": "#784c0d",
                "secondary-fixed": "#d4eca2",
                "surface-container-high": "#ebe8e3",
                "outline": "#8b716b",
                "primary-fixed-dim": "#ffb4a2",
                "on-error": "#ffffff",
                "tertiary-fixed-dim": "#f8bb73",
                "on-surface-variant": "#58423c",
                "on-secondary-fixed": "#141f00",
                "tertiary-fixed": "#ffddb9",
                "primary-container": "#bd472a",
                "on-tertiary-fixed-variant": "#663e00"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "margin-mobile": "16px",
                "margin-desktop": "40px",
                "unit": "8px",
                "gutter": "24px",
                "container-max": "1200px"
            },
            "fontFamily": {
                "body-lg": ["Be Vietnam Pro"],
                "headline-md": ["Noto Serif"],
                "headline-xl": ["Noto Serif"],
                "headline-lg": ["Noto Serif"],
                "body-md": ["Be Vietnam Pro"],
                "headline-lg-mobile": ["Noto Serif"],
                "caption": ["Be Vietnam Pro"],
                "label-md": ["Be Vietnam Pro"]
            },
            "fontSize": {
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
                "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
                "caption": ["12px", {"lineHeight": "16px", "fontWeight": "400"}],
                "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}]
            }
        },
    },
}